function print_for_publication(filename, papersize, margins)

set(gcf, ...
    'PaperUnits',        'inches', ...
    'PaperSize',         papersize, ...
    'PaperPositionMode', 'manual', ...
    'PaperPosition',     [0 0 papersize]);

newpos = get(gcf, 'PaperPosition') + margins - [0 0 margins(1:2)];

set(gca, ...
    'Units', 'inches', ...
    'Position', newpos);
         
print('-dpdf', filename);         