function print_for_publication(filename, papersize, margins)

set(gcf, ...
    'PaperUnits',        'inches', ...
    'PaperSize',         papersize, ...
    'PaperPositionMode', 'manual', ...
    'PaperPosition',     [0 0 papersize]);

newpos = get(gcf, 'PaperPosition') + margins - [0 0 margins(1:2)];

a = findobj(gcf, 'Type', 'axes');  % not subfigure compatible!

set(a, ...
    'Units', 'inches', ...
    'Position', newpos);
         
print('-dpdf', filename);         